name: 'Infra-Lens'
description: 'AI-powered analysis and summarization of infrastructure changes with risk assessment and deployment recommendations'
author: 'Pauly-DData <paulydriessens@gmail.com>'

inputs:
  openai-api-key:
    description: 'OpenAI API key for generating AI summaries'
    required: true
  cdk-diff-file:
    description: 'Path to the CDK diff JSON file'
    required: false
    default: 'cdk-diff.json'
  output-format:
    description: 'Output format for the summary'
    required: false
    default: 'markdown'
    type: choice
    options:
      - markdown
      - json
      - html
  language:
    description: 'Language for the summary'
    required: false
    default: 'en'
    type: choice
    options:
      - en
      - nl
  model:
    description: 'OpenAI model to use for summarization'
    required: false
    default: 'gpt-4'
  max-tokens:
    description: 'Maximum tokens for the summary'
    required: false
    default: '500'
  fail-on-destructive:
    description: 'Fail the workflow if destructive changes are detected'
    required: false
    default: 'false'
  post-comment:
    description: 'Post summary as PR comment'
    required: false
    default: 'true'
  create-issue:
    description: 'Create GitHub issue if no PR is found'
    required: false
    default: 'false'

outputs:
  summary:
    description: 'The generated AI summary'
  risk-score:
    description: 'Risk assessment score (0-100)'
  success:
    description: 'Whether the action completed successfully'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run CDK Diff Summarizer
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        python ${{ github.action_path }}/src/main.py
      env:
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        CDK_DIFF_FILE: ${{ inputs.cdk-diff-file }}
        OUTPUT_FORMAT: ${{ inputs.output-format }}
        LANGUAGE: ${{ inputs.language }}
        MODEL: ${{ inputs.model }}
        MAX_TOKENS: ${{ inputs.max-tokens }}
        FAIL_ON_DESTRUCTIVE: ${{ inputs.fail-on-destructive }}
        POST_COMMENT: ${{ inputs.post-comment }}
        CREATE_ISSUE: ${{ inputs.create-issue }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}

branding:
  icon: 'cloud'
  color: 'blue' 