"""GitHub posting + output formatting for Infra-Lens."""

import json
import os
import time
from typing import Any, Dict, Optional

from github import Github

from config import Config, OutputFormat


class GitHubService:
    """Posts summaries to PR comments / issues and writes Action outputs."""

    def __init__(self, config: Config):
        self.config = config
        self.github_config = config.github
        self.client = Github(self.github_config.token) if self.github_config else None

    def post_summary(self, summary: str) -> Optional[int]:
        """Post the summary based on post_comment / create_issue flags.

        Returns the PR/issue number that received the comment, if any.
        """
        if not self.client or not self.github_config:
            return None

        try:
            repo = self.client.get_repo(self.github_config.repository)
            event_data = self._get_event_data()
            pr_number = self._get_pr_number(event_data) if event_data else None

            posted_to = None

            if self.github_config.post_comment and pr_number:
                try:
                    pr = repo.get_pull(int(pr_number))
                    pr.create_issue_comment(summary)
                    print(f"::notice::Posted summary as comment on PR #{pr_number}")
                    posted_to = pr_number
                except Exception as e:
                    print(f"::error::Failed to comment on PR #{pr_number}: {e}")

            if self.github_config.create_issue and posted_to is None:
                try:
                    title = (
                        f"Infra-Lens summary — {time.strftime('%Y-%m-%d %H:%M UTC')}"
                    )
                    issue = repo.create_issue(title=title, body=summary)
                    print(f"::notice::Created issue #{issue.number}")
                    posted_to = issue.number
                except Exception as e:
                    print(f"::error::Failed to create issue: {e}")

            if posted_to is None and not (
                self.github_config.post_comment or self.github_config.create_issue
            ):
                print("::notice::Both post-comment and create-issue are disabled")

            return posted_to

        except Exception as e:
            print(f"::error::Failed to post to GitHub: {e}")
            return None

    def _get_event_data(self) -> Optional[Dict[str, Any]]:
        if not self.github_config or not self.github_config.event_path:
            return None
        try:
            with open(self.github_config.event_path, "r") as f:
                return json.load(f)
        except Exception as e:
            print(f"::warning::Could not read event payload: {e}")
            return None

    def _get_pr_number(self, event_data: Dict[str, Any]) -> Optional[int]:
        if "pull_request" in event_data:
            return event_data["pull_request"]["number"]
        if event_data.get("issue", {}).get("pull_request"):
            return event_data["issue"]["number"]
        env_pr = os.getenv("GITHUB_PR_NUMBER")
        if env_pr and env_pr.isdigit():
            return int(env_pr)
        return None

    def set_output(self, name: str, value: str):
        """Write to $GITHUB_OUTPUT using the heredoc form (supports multi-line)."""
        if not self.github_config or not self.github_config.output_path:
            return
        try:
            delimiter = f"ghadelimiter_{int(time.time() * 1000)}"
            with open(self.github_config.output_path, "a") as f:
                f.write(f"{name}<<{delimiter}\n{value}\n{delimiter}\n")
        except Exception as e:
            print(f"::warning::Failed to set output {name}: {e}")


class OutputFormatter:
    """Renders the summary as markdown / JSON / HTML."""

    @staticmethod
    def format_output(
        summary: str,
        output_format: OutputFormat,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> str:
        metadata = metadata or {}
        if output_format == OutputFormat.JSON:
            return OutputFormatter._json(summary, metadata)
        if output_format == OutputFormat.HTML:
            return OutputFormatter._html(summary, metadata)
        return OutputFormatter._markdown(summary, metadata)

    @staticmethod
    def _markdown(summary: str, metadata: Dict[str, Any]) -> str:
        footer_parts = []
        if "model" in metadata:
            footer_parts.append(f"`{metadata['model']}`")
        if "timestamp" in metadata:
            footer_parts.append(metadata["timestamp"])
        footer = " · ".join(footer_parts)
        if footer:
            return (
                f"{summary}\n\n"
                f"<sub>Generated by [Infra-Lens](https://github.com/CloudLabOne/Infra-Lens) "
                f"· {footer}</sub>"
            )
        return summary

    @staticmethod
    def _json(summary: str, metadata: Dict[str, Any]) -> str:
        return json.dumps(
            {
                "summary": summary,
                "metadata": metadata,
                "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            },
            indent=2,
        )

    @staticmethod
    def _html(summary: str, metadata: Dict[str, Any]) -> str:
        """Minimal HTML wrapper. Caller is responsible for converting markdown
        to HTML if richer rendering is needed — naive replace was producing
        broken markup, so we wrap the raw markdown in a <pre> block instead.
        """
        import html as _html

        escaped = _html.escape(summary)
        model = _html.escape(str(metadata.get("model", "")))
        timestamp = _html.escape(str(metadata.get("timestamp", "")))
        return (
            "<!doctype html>\n"
            "<html><head><meta charset=\"utf-8\">"
            "<title>Infra-Lens summary</title>"
            "<style>"
            "body{font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;"
            "max-width:760px;margin:2.5rem auto;padding:0 1.25rem;color:#111}"
            "pre{background:#f6f8fa;padding:1rem;border-radius:8px;"
            "white-space:pre-wrap;word-wrap:break-word}"
            "footer{margin-top:2rem;color:#666;font-size:0.85rem}"
            "</style></head><body>"
            "<h1>Infra-Lens summary</h1>"
            f"<pre>{escaped}</pre>"
            f"<footer>{model} · {timestamp}</footer>"
            "</body></html>"
        )
